FROM openjdk:11-jre-slim

# List the contents of the target directory for debugging

# Copy the jar file into the image
# ADD zipkin-service.jar zipkin-service.jar

EXPOSE 8767

# Specify the command to run the jar file
CMD ["java", "-jar", "zipkin-service.jar"]

